---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-app
  namespace: flux-system
spec:
  interval: 30s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-app
  targetNamespace: default
  patches:
  - patch: |-
      apiVersion: autoscaling/v2beta2
      kind: HorizontalPodAutoscaler
      metadata:
        name: kube-app
      spec:
        minReplicas: 3
    target: 
      name: kube-app
      kind: HorizontalPodAutoscaler
